# Generated by Django 5.1.3 on 2025-02-06 04:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='プロジェクト名')),
                ('description', models.TextField(blank=True, verbose_name='説明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': 'プロジェクト',
                'verbose_name_plural': 'プロジェクト',
            },
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='タイトル')),
                ('description', models.TextField(blank=True, verbose_name='説明')),
                ('preconditions', models.TextField(blank=True, verbose_name='前提条件')),
                ('steps', models.TextField(verbose_name='テストステップ')),
                ('expected_result', models.TextField(verbose_name='期待される結果')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
            ],
            options={
                'verbose_name': 'テストケース',
                'verbose_name_plural': 'テストケース',
            },
        ),
        migrations.CreateModel(
            name='TestPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='プラン名')),
                ('description', models.TextField(blank=True, verbose_name='説明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_management.project', verbose_name='プロジェクト')),
            ],
            options={
                'verbose_name': 'テストプラン',
                'verbose_name_plural': 'テストプラン',
            },
        ),
        migrations.CreateModel(
            name='TestPlanCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0, verbose_name='実行順序')),
                ('test_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_management.testcase', verbose_name='テストケース')),
                ('test_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_management.testplan', verbose_name='テストプラン')),
            ],
            options={
                'verbose_name': 'テストプランケース',
                'verbose_name_plural': 'テストプランケース',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='testplan',
            name='test_cases',
            field=models.ManyToManyField(through='test_management.TestPlanCase', to='test_management.testcase', verbose_name='テストケース'),
        ),
        migrations.CreateModel(
            name='TestRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='実行名')),
                ('description', models.TextField(blank=True, verbose_name='説明')),
                ('status', models.CharField(choices=[('not_started', '未開始'), ('in_progress', '実行中'), ('completed', '完了')], default='not_started', max_length=20, verbose_name='ステータス')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('assigned_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='担当者')),
                ('test_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_management.testplan', verbose_name='テストプラン')),
            ],
            options={
                'verbose_name': 'テスト実行',
                'verbose_name_plural': 'テスト実行',
            },
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('passed', '合格'), ('failed', '不合格'), ('blocked', 'ブロック'), ('skipped', 'スキップ')], max_length=20, verbose_name='結果')),
                ('comment', models.TextField(blank=True, verbose_name='コメント')),
                ('executed_at', models.DateTimeField(auto_now_add=True, verbose_name='実行日時')),
                ('executed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='実行者')),
                ('test_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_management.testcase', verbose_name='テストケース')),
                ('test_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_management.testrun', verbose_name='テスト実行')),
            ],
            options={
                'verbose_name': 'テスト結果',
                'verbose_name_plural': 'テスト結果',
            },
        ),
        migrations.CreateModel(
            name='TestSuite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='スイート名')),
                ('description', models.TextField(blank=True, verbose_name='説明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_management.project', verbose_name='プロジェクト')),
            ],
            options={
                'verbose_name': 'テストスイート',
                'verbose_name_plural': 'テストスイート',
            },
        ),
        migrations.AddField(
            model_name='testcase',
            name='suite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_management.testsuite', verbose_name='テストスイート'),
        ),
    ]
