# Generated by Django 5.1.3 on 2025-02-06 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_management', '0002_bug'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestCaseAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='test_case_attachments/%Y/%m/%d/', verbose_name='ファイル')),
                ('filename', models.CharField(max_length=255, verbose_name='ファイル名')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='アップロード日時')),
                ('test_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='test_management.testcase', verbose_name='テストケース')),
            ],
            options={
                'verbose_name': 'テストケース添付ファイル',
                'verbose_name_plural': 'テストケース添付ファイル',
            },
        ),
    ]
