# Generated by Django 5.1.3 on 2025-02-07 01:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_management', '0003_testcaseattachment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='current_version',
            field=models.IntegerField(default=1, verbose_name='現在のバージョン'),
        ),
        migrations.CreateModel(
            name='TestCaseHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='タイトル')),
                ('description', models.TextField(blank=True, verbose_name='説明')),
                ('preconditions', models.TextField(blank=True, verbose_name='前提条件')),
                ('steps', models.TextField(verbose_name='テストステップ')),
                ('expected_result', models.TextField(verbose_name='期待される結果')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='変更日時')),
                ('change_comment', models.TextField(blank=True, verbose_name='変更コメント')),
                ('version', models.IntegerField(verbose_name='バージョン')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='変更者')),
                ('test_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='test_management.testcase', verbose_name='テストケース')),
            ],
            options={
                'verbose_name': 'テストケース履歴',
                'verbose_name_plural': 'テストケース履歴',
                'ordering': ['-version'],
            },
        ),
    ]
