# Generated by Django 5.1.3 on 2025-02-07 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_management', '0004_testcase_current_version_testcasehistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testcasehistory',
            name='description',
        ),
        migrations.RemoveField(
            model_name='testcasehistory',
            name='expected_result',
        ),
        migrations.RemoveField(
            model_name='testcasehistory',
            name='preconditions',
        ),
        migrations.RemoveField(
            model_name='testcasehistory',
            name='steps',
        ),
        migrations.RemoveField(
            model_name='testcasehistory',
            name='title',
        ),
        migrations.AddField(
            model_name='testcasehistory',
            name='description_diff',
            field=models.TextField(blank=True, verbose_name='説明の差分'),
        ),
        migrations.AddField(
            model_name='testcasehistory',
            name='expected_result_diff',
            field=models.TextField(blank=True, verbose_name='期待される結果の差分'),
        ),
        migrations.AddField(
            model_name='testcasehistory',
            name='preconditions_diff',
            field=models.TextField(blank=True, verbose_name='前提条件の差分'),
        ),
        migrations.AddField(
            model_name='testcasehistory',
            name='steps_diff',
            field=models.TextField(blank=True, verbose_name='テストステップの差分'),
        ),
        migrations.AddField(
            model_name='testcasehistory',
            name='title_diff',
            field=models.TextField(blank=True, verbose_name='タイトルの差分'),
        ),
    ]
